[package]
name = "iex-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "2", features = ["full", "visit-mut"] }
quote = "1"
darling = "0.20"
